### PR TITLE
small bugfixes in memory modeling 

### PR DESCRIPTION
**Pull request by sifislag**

### CODE REVIEW

**Comment by snf** [comment]
I think this may bring issues later as values won't be classified as NumericValues? Also last time I checked the values saturated to 0x7fffffff.

Still have this PR here which is probably not the correct solution either: https://github.com/nevillegrech/gigahorse-toolchain/pull/42/files . The reason I went for it is because most of the ones I observed were negative.

**Comment by sifislag** [comment]
Hi @snf, my reasoning is that `Variable_NumericValue()` will contain the subset of `Variable_Value()` that we can model with souffle's arithmetic. I had a quick look through the uses and it looked consistent with what I had in mind. In all other cases we can use `Variable_Value()` directly. Do you want us to revisit your PR based on an example?
You're right about `0x7fffffff`, changing it.

**Comment by sifislag** [comment]
Went with a different approach to solving your problem in my latest commit. Check it out and let me know what you think.

**Comment by snf** [comment]
I cannot try til next week but it looks good to me. Thanks for the change

**Comment by sifislag** [comment]
Thanks for your input! Let me know when you're able to check it.

**Pull request merged**
